name: 01 - Building Blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World"
    echo-bye:
        runs-on: ubuntu-latest
        steps:
            - name: Failed Step
              run: |
                echo "I will Succed"
                exit 0
            - name: Say Goodbye
              run: echo "Goodbye"
            