name: 02 - Workflow Events

on: push
jobs:
  echo:
    runs-on: ubuntu:latest
    steps:
        - name: Show the trigger
          run: echo "I have been trigered by an ${{github.event_name}} event."  